kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: microservice-c
spec:
  destination:
    kind: ServiceAccount
    name: microservice-c-sa
    namespace: a0005-i
  rules:
  - kind: HTTPRouteGroup
    name: microservice-c
    matches:
    - url-caller
  sources:
  - kind: ServiceAccount
    name: microservice-b-sa
    namespace: a0005-o
---
apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: microservice-c
spec:
  matches:
  - name: url-caller
    pathRegex: /URLCaller/depth/.+
    methods:
    - GET